DROP DATABASE WAFFLE;
CREATE DATABASE WAFFLE;
USE WAFFLE;

--CATEGORIAS


CREATE TABLE [dbo].[CATEGORIA](
	[ID] [int] NOT NULL,
	[NOMBRE] [varchar](50) NOT NULL,
 CONSTRAINT [PK_CATEGORIA] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
	--INSERTAR
CREATE PROCEDURE [dbo].[CRE_CATEGORIA_PR]
	@ID int,
	@NOMBRE varchar(50)
AS INSERT INTO [dbo].[CATEGORIA] VALUES(@ID,@NOMBRE);
GO

	--RETRIEVE ALL
CREATE PROCEDURE [dbo].[RET_ALL_CATEGORIA_PR]
AS
	SELECT ID, NOMBRE FROM CATEGORIA;
RETURN 0
GO

	--UPDATE
CREATE PROCEDURE [dbo].[UPD_CATEGORIA_PR]
	@ID int,
	@NOMBRE varchar(50)
AS 
	UPDATE [dbo].[CATEGORIA] SET NOMBRE=@NOMBRE WHERE ID=@ID;
GO

	--RETRIEVE BY ID
CREATE PROCEDURE [dbo].[RET_CATEGORIA_PR]
	@ID int
AS
	SELECT ID, NOMBRE FROM CATEGORIA WHERE ID=@ID
RETURN 0
GO

	--DELETE
CREATE PROCEDURE [dbo].[DEL_CATEGORIA_PR]
	@ID int
AS
	DELETE FROM CATEGORIA WHERE ID=@ID;
RETURN 0
GO



--DIRECCIONES


CREATE TABLE [dbo].[DIRECCION](
	[ID] [int] NOT NULL,
	[LATITUD] [varchar](50) NOT NULL,
	[LONGITUD] [varchar](50) NOT NULL,
 CONSTRAINT [PK_DIRECCION] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE PROCEDURE [dbo].[CRE_DIRECCION_PR]
	@ID INT,
	@LATITUD VARCHAR(50),
	@LONGITUD VARCHAR(50)
AS
	INSERT INTO DIRECCION VALUES(@ID,@LATITUD,@LONGITUD);
GO


--USUARIOS
CREATE TABLE [dbo].[USUARIO](
	[CEDULA] [varchar](50) NOT NULL,
	[NOMBRE] [varchar](50) NOT NULL,
	[APELLIDO1] [varchar](50) NOT NULL,
	[APELLIDO2] [varchar](50) NULL,
	[CORREO] [varchar](50) NOT NULL,
	[CONTRASENA] [varchar](50) NOT NULL,
	[TEL] [varchar](50) NOT NULL,
	[PAYPAL] [varchar](50) NOT NULL,
	[FOTO_PERFIL] [varchar](50) NULL,
	[ESTADO] [bit] NOT NULL,
	[TIPO_IDENTIFICACION] [varchar](50) NOT NULL,
	[CODIGO_VERIFICACION] [varchar](50) NOT NULL,
 CONSTRAINT [PK_USUARIO] PRIMARY KEY CLUSTERED 
(
	[CEDULA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

--CADENAS
CREATE TABLE [dbo].[CADENA](
	[ID] [int] NOT NULL,
	[CEDULA_DUENNIO] [varchar](50) NOT NULL,
	[LOGO] [varchar](100) NOT NULL,
 CONSTRAINT [PK_CADENA] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CADENA]  WITH CHECK ADD  CONSTRAINT [FK_USUARIO_CADENA] FOREIGN KEY([CEDULA_DUENNIO])
REFERENCES [dbo].[USUARIO] ([CEDULA])
GO

ALTER TABLE [dbo].[CADENA] CHECK CONSTRAINT [FK_USUARIO_CADENA]
GO


--COMERCIOS

CREATE TABLE COMERCIO(
	[CEDULA_JURIDICA] [varchar](50) NOT NULL,
	[CEDULA_DUENO] [varchar](50) NOT NULL,
	[ID_DIRECCION] [int] NOT NULL,
	[ID_CATEGORIA] [int] NOT NULL,
	[ID_CADENA] [int] NOT NULL,
	[REGIMEN] [varchar](50) NOT NULL,
	[TELEFONO] [varchar](50) NOT NULL,
	[HORARIO_APERTURA] [time](7) NOT NULL,
	[HORARIO_CLAUSURA] [time](7) NOT NULL,
	[UBICACION_ESCRITA] [varchar](50) NOT NULL,
	[NOMBRE_COMERCIAL] [varchar](50) NOT NULL,
	[FECHA_CREACION] [date] NOT NULL,
	[WEB] [varchar](50) NOT NULL,
	[ESTADO] [varchar](10) NOT NULL,
	[SUPERVISOR] [varchar](50) NOT NULL,
 CONSTRAINT [PK_COMERCIO] PRIMARY KEY CLUSTERED 
(
	[CEDULA_JURIDICA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[COMERCIO]  WITH CHECK ADD  CONSTRAINT [FK_CADENA_COMERCIO] FOREIGN KEY([ID_CADENA])
REFERENCES [dbo].[CADENA] ([ID])
GO

ALTER TABLE [dbo].[COMERCIO] CHECK CONSTRAINT [FK_CADENA_COMERCIO]
GO

ALTER TABLE [dbo].[COMERCIO]  WITH CHECK ADD  CONSTRAINT [FK_CATEGORIA_COMERCIO] FOREIGN KEY([ID_CATEGORIA])
REFERENCES [dbo].[CATEGORIA] ([ID])
GO

ALTER TABLE [dbo].[COMERCIO] CHECK CONSTRAINT [FK_CATEGORIA_COMERCIO]
GO

ALTER TABLE [dbo].[COMERCIO]  WITH CHECK ADD  CONSTRAINT [FK_DIRECCION_COMERCIO] FOREIGN KEY([ID_DIRECCION])
REFERENCES [dbo].[DIRECCION] ([ID])
GO

ALTER TABLE [dbo].[COMERCIO] CHECK CONSTRAINT [FK_DIRECCION_COMERCIO]
GO

ALTER TABLE [dbo].[COMERCIO]  WITH CHECK ADD  CONSTRAINT [FK_DUENO_COMERCIO] FOREIGN KEY([CEDULA_DUENO])
REFERENCES [dbo].[USUARIO] ([CEDULA])
GO

ALTER TABLE [dbo].[COMERCIO] CHECK CONSTRAINT [FK_DUENO_COMERCIO]
GO

ALTER TABLE [dbo].[COMERCIO]  WITH CHECK ADD  CONSTRAINT [FK_SUPERVISOR_COMERCIO] FOREIGN KEY([SUPERVISOR])
REFERENCES [dbo].[USUARIO] ([CEDULA])
GO

ALTER TABLE [dbo].[COMERCIO] CHECK CONSTRAINT [FK_SUPERVISOR_COMERCIO]
GO

	--INSERT
CREATE PROCEDURE [dbo].[CRE_COMERCIO_PR]
	@CEDULA_JURIDICA VARCHAR(50),
	@CEDULA_DUENO VARCHAR(50),
	@ID_DIRECCION INT,
	@ID_CATEGORIA INT,
	@ID_CADENA INT,
	@REGIMEN VARCHAR(50),
	@TELEFONO VARCHAR(50),
	@HORARIO_APERTURA TIME(7),
	@HORARIO_CLAUSURA TIME(7),
	@UBICACION_ESCRITA VARCHAR(50),
	@NOMBRE_COMERCIAL VARCHAR(50),
	@FECHA_CREACION DATE,
	@WEB VARCHAR(50),
	@ESTADO VARCHAR(10),
	@SUPERVISOR VARCHAR(50)
AS INSERT INTO COMERCIO VALUES (@CEDULA_JURIDICA,@CEDULA_DUENO,@ID_DIRECCION,@ID_CADENA,@ID_CADENA,@REGIMEN,@TELEFONO,
		@HORARIO_APERTURA,@HORARIO_CLAUSURA,@UBICACION_ESCRITA,@NOMBRE_COMERCIAL,@FECHA_CREACION,@WEB,@ESTADO,@SUPERVISOR);
	GO

	--RETRIEVE ALL
CREATE PROCEDURE [dbo].[RET_ALL_COMERCIO_PR]
AS SELECT CEDULA_JURIDICA,CEDULA_DUENO,ID_DIRECCION,ID_CATEGORIA,ID_CADENA,REGIMEN,TELEFONO,HORARIO_APERTURA,HORARIO_CLAUSURA,
	UBICACION_ESCRITA,NOMBRE_COMERCIAL,FECHA_CREACION,WEB,ESTADO,SUPERVISOR FROM COMERCIO;
RETURN 0
GO
--FLOTILLAS

CREATE TABLE [dbo].[FLOTILLA](
	[ID] [int] NOT NULL,
	[NOMBRE] [varchar](50) NOT NULL,
	[DESCRIPCION] [varchar](50) NULL,
 CONSTRAINT [PK_FLOTILLA] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


--HISTORIAL DE CONTRASEÑAS

CREATE TABLE [dbo].[HISTORICO_CONTRASENA](
	[FECHA] [date] NOT NULL,
	[CEDULA_USUARIO] [varchar](50) NOT NULL,
	[CONTRASENA] [varchar](50) NOT NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[HISTORICO_CONTRASENA]  WITH CHECK ADD  CONSTRAINT [FK_USUARIO_HISTORICO] FOREIGN KEY([CEDULA_USUARIO])
REFERENCES [dbo].[USUARIO] ([CEDULA])
GO

ALTER TABLE [dbo].[HISTORICO_CONTRASENA] CHECK CONSTRAINT [FK_USUARIO_HISTORICO]
GO


--MEMBRESIAS
CREATE TABLE [dbo].[MEMBRESIA](
	[CODIGO_MEMBRESIA] [varchar](50) NOT NULL,
	[CEDULA_USUARIO] [varchar](50) NOT NULL,
	[MONTO] [float] NOT NULL,
	[FECHA_COMPRADA] [date] NOT NULL,
	[FECHA_EXPIRADA] [date] NOT NULL,
	[COMISION_PEDIDO] [float] NOT NULL,
	[TIPO_MEMBRESIA] [varchar](50) NOT NULL,
 CONSTRAINT [PK_MEMBRESIA] PRIMARY KEY CLUSTERED 
(
	[CODIGO_MEMBRESIA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[MEMBRESIA]  WITH CHECK ADD  CONSTRAINT [FK_USUARIO_MEMBRESIA] FOREIGN KEY([CEDULA_USUARIO])
REFERENCES [dbo].[USUARIO] ([CEDULA])
GO

ALTER TABLE [dbo].[MEMBRESIA] CHECK CONSTRAINT [FK_USUARIO_MEMBRESIA]
GO




--VEHICULOS

CREATE TABLE [dbo].[VEHICULO](
	[PLACA] [varchar](50) NOT NULL,
	[MODELO] [varchar](50) NOT NULL,
	[TIPO] [varchar](50) NOT NULL,
	[CEDULA_DUENNIO] [varchar](50) NOT NULL,
	[ID_FLOTILLA] [int] NULL,
 CONSTRAINT [PK_VEHICULO] PRIMARY KEY CLUSTERED 
(
	[PLACA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[VEHICULO]  WITH CHECK ADD  CONSTRAINT [FK_DUENNIO] FOREIGN KEY([CEDULA_DUENNIO])
REFERENCES [dbo].[USUARIO] ([CEDULA])
GO

ALTER TABLE [dbo].[VEHICULO] CHECK CONSTRAINT [FK_DUENNIO]
GO

ALTER TABLE [dbo].[VEHICULO]  WITH CHECK ADD  CONSTRAINT [FK_FLOTILLA] FOREIGN KEY([ID_FLOTILLA])
REFERENCES [dbo].[FLOTILLA] ([ID])
GO

ALTER TABLE [dbo].[VEHICULO] CHECK CONSTRAINT [FK_FLOTILLA]
GO

--PRODUCTOS

CREATE TABLE [dbo].[PRODUCTO](
	[ID] [int] NOT NULL,
	[NOMBRE] [varchar](50) NOT NULL,
	[ID_CATEGORIA] [int] NOT NULL,
	[CEDULA_COMERCIO] [varchar](50) NOT NULL,
	[PRECIO] [float] NOT NULL,
	[ESTADO] [varchar](10) NOT NULL,
	CONSTRAINT [PK_PRODUCTO] PRIMARY KEY CLUSTERED
	(
		[ID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]
	GO

ALTER TABLE [dbo].[PRODUCTO] WITH CHECK ADD CONSTRAINT [FK_COMERCIO] FOREIGN KEY([CEDULA_COMERCIO])
REFERENCES [dbo].[COMERCIO] ([CEDULA_JURIDICA])
GO

ALTER TABLE [dbo].[PRODUCTO] CHECK CONSTRAINT [FK_COMERCIO]
GO

ALTER TABLE [dbo].[PRODUCTO] WITH CHECK ADD CONSTRAINT [FK_CATEGORIA] FOREIGN KEY([ID_CATEGORIA])
REFERENCES [dbo].[CATEGORIA] ([ID])
GO

ALTER TABLE [dbo].[PRODUCTO] CHECK CONSTRAINT [FK_CATEGORIA]
GO

--ORDENES
CREATE TABLE [dbo].[ORDEN](
	[ID] [int] NOT NULL,
	[ID_DIRECCION] [int] NOT NULL,
	[CEDULA_USUARIO] [varchar](50) NOT NULL,
	[CEDULA_COMERCIO] [varchar](50) NOT NULL,
	[CEDULA_CONDUCTOR] [varchar](50) NOT NULL,
	[ESTADO] [varchar](50) NOT NULL,
	[FECHA] [date] NOT NULL,
	CONSTRAINT [PK_ORDEN] PRIMARY KEY CLUSTERED
	(
		[ID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]
	GO

ALTER TABLE [dbo].[ORDEN] WITH CHECK ADD CONSTRAINT [FK_USUARIO_FINAL] FOREIGN KEY([CEDULA_USUARIO])
REFERENCES [dbo].[USUARIO] ([CEDULA])
GO

ALTER TABLE [dbo].[ORDEN] CHECK CONSTRAINT [FK_USUARIO_FINAL]
GO

ALTER TABLE [dbo].[ORDEN] WITH CHECK ADD CONSTRAINT [FK_TRANSPORTISTA] FOREIGN KEY([CEDULA_CONDUCTOR])
REFERENCES [dbo].[USUARIO] ([CEDULA])
GO

ALTER TABLE [dbo].[ORDEN] CHECK CONSTRAINT [FK_TRANSPORTISTA]
GO

ALTER TABLE [dbo].[ORDEN] WITH CHECK ADD CONSTRAINT [FK_COMERCIO_ORDEN] FOREIGN KEY([CEDULA_COMERCIO]) REFERENCES [dbo].[COMERCIO] ([CEDULA_JURIDICA])
GO

ALTER TABLE [dbo].[ORDEN] CHECK CONSTRAINT [FK_COMERCIO_ORDEN]
GO

--DETALLES DE ORDEN
CREATE TABLE [dbo].[ORDEN_DETALLE](
	[ID] [int] NOT NULL,
	[ID_ORDEN] [int] NOT NULL,
	[ID_PRODUCTO] [int] NOT NULL,
	[NOMBRE_PRODUCTO] [varchar](50) NOT NULL,
	[PRECIO] [float] NOT NULL,
	[CANTIDAD] [int] NOT NULL,
	[CALIFICACION] [int] NOT NULL,
	CONSTRAINT [PK_ORDEN_DETALLE] PRIMARY KEY CLUSTERED
	(
		[ID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]
	GO

ALTER TABLE [dbo].[ORDEN_DETALLE] WITH CHECK ADD CONSTRAINT [FK_ORDEN] FOREIGN KEY ([ID_ORDEN])
REFERENCES [dbo].[ORDEN] ([ID])
GO

--EXCEPCIONES
CREATE TABLE [dbo].[EXCEPCION](
	[ID] int NOT NULL PRIMARY KEY,
	[MENSAJE] varchar(500) NOT NULL
	);

INSERT INTO EXCEPCION VALUES(0,'Error.');
INSERT INTO EXCEPCION VALUES(1,'Identificador no válido.');
INSERT INTO EXCEPCION VALUES(2,'El cliente debe tener 15 años para registrarse.');
INSERT INTO EXCEPCION VALUES(3,'El cliente debe tener 18 años para pedir bebidas alcohólicas.');
INSERT INTO EXCEPCION VALUES(4,'Ya existe una entrada registrada con esa identifiación.');
GO
	--RETRIEVE ALL
CREATE PROCEDURE [dbo].[RET_ALL_EXCEPCION_PR]
AS
	SELECT ID, MENSAJE FROM EXCEPCION;
RETURN 0
GO

	--RETRIEVE
CREATE PROCEDURE [dbo].[RET_EXCEPCION_PR]
	@ID int
AS
	SELECT ID, MENSAJE FROM EXCEPCION WHERE ID=@ID;
RETURN 0
GO

--MONEDERO
CREATE TABLE [dbo].[MONEDERO](
	ID int PRIMARY KEY,
	CEDULA_USUARIO varchar(50) FOREIGN KEY REFERENCES USUARIO(CEDULA),
	SALDO float NOT NULL
	);
	GO

	--INSERT
CREATE PROCEDURE [dbo].[CRE_MONEDERO_PR]
	@ID INT,
	@CEDULA_USUARIO VARCHAR(50)
AS
	INSERT INTO MONEDERO VALUES(@ID,@CEDULA_USUARIO,0);
GO

	--RETRIEVE BY USER ID
CREATE PROCEDURE [dbo].[RET_MONEDERO_PR]
	@CEDULA_USUARIO VARCHAR(50)
AS
	SELECT ID, CEDULA_USUARIO, SALDO FROM MONEDERO WHERE CEDULA_USUARIO=@CEDULA_USUARIO;
GO

